Improve return types for psalm
loophp/collection pull request #321
Opened 2023-11-23 19:58 UTC by Matth--

Psalm cannot always infer the types when not defining the CollectionInterface<Key, Value> type. This makes sure that psalm is aware of the implemented interface and the Collection class.

This PR:

- [x] Fix #318 
- [x] Has static analysis tests (psalm, phpstan)

Still open for debate as it changes the static constructor types.

2023-11-23 20:04 UTC, drupol commented
Psalm 5.16 has been released yesterday and adds many new issues. I guess we will have to add them to the baseline.

2023-11-23 20:08 UTC, drupol commented
Can you please run:

1. Fix CS: `./vendor/bin/grumphp run --tasks=phpcsfixer`
2. Commit
3. Fix Psalm baseline: `./vendor/bin/psalm --set-baseline=psalm-baseline.xml`
4. Commit
5. Push

2023-11-24 05:44 UTC, drupol requested changes
Thanks for your contribution! Much appreciated 👍

There's one missing thing. The CollectionDecorator class also needs to be updated with the same changes, and then it's good to go.

2023-11-24 05:46 UTC, Matth-- commented
@drupol Missed that one as I haven't used it before 😅 . Will update soon!

2023-11-24 05:46 UTC, drupol commented
Merci ❤️

2023-11-24 08:31 UTC, Matth-- commented
Tried to implement something similar for the CollectionDecorator but now phpstan is complaining. I will need to do more investigation to be able to fix this.

2023-11-24 08:34 UTC, drupol commented
Oh curious, what are the issues?

2023-11-24 09:26 UTC, Matth-- commented
After changing the `fromIterable` method to this in the `CollectionDecorator` class

```php
  /**
   * @template UKey
   * @template U
   *
   * @param iterable<UKey, U> $iterable
   *
   * @return CollectionInterface<UKey, U>&static<UKey, U>
   */
  public static function fromIterable(iterable $iterable): CollectionInterface
  {
      return new static(Collection::fromIterable($iterable));
  }
```

I get the psalm error:

```
ERROR: MixedArgument
at /path/collection/tests/static-analysis/fromIterableAssociateAll.php:31:11
Argument 1 of checklist cannot be mixed, expecting array<string, int> (see https://psalm.dev/030)
checklist(CollectionDecorator::fromIterable(fromIterableAssociateAll::cases())->associate(
    static fn (int $_, fromIterableAssociateAll $item): int => $item->value,
    static fn (fromIterableAssociateAll $item, int $_): string => $item->name,
)->flip()->all(false));

```

And phpstan spits out:

```

2023-11-24 09:36 UTC, drupol commented
OK fair enough, let's not update `CollectionDecorator` in this PR then.

Was the closing of the PR intentional ?

2023-11-24 10:19 UTC, Matth-- commented
Nope sorry :)

2023-11-24 10:20 UTC, drupol commented
OK cool ! :) Let me know when it's done for you and I'll take care of the rest.

2023-11-24 21:34 UTC, drupol commented
@Matth-- Is it ready to be merged for you?

2023-11-25 04:12 UTC, Matth-- commented
I would say yes for now. 🚀 

 I'd like to find the root of the problem when i have some more time. Might have to look at the psalm package then.

2023-11-25 07:44 UTC, merged

2023-11-25 07:45 UTC, drupol commented
OK, let's do that. Let me know if I can do further things to improve this project!

Thanks again for your contribution, keep them coming 👍